### PR TITLE
use 'cmd' instead of 'alt' on osx

### PR DESCRIPTION
**Pull request by karljs**
As mentioned in issue #116

I'm not familiar at all with Atom package development, so please let me know if this is not the right way to go about this.

### CODE REVIEW

**Comment by archaeron** [comment]
@edwinb since this affects your book, is it okay for you if I merge this?

**Comment by crakjie** [comment]
cmd+shift+key should not be even more easy to use?

**Comment by karljs** [comment]
@crakjie I would be happy with cmd+shift as well.  I typically swap ctrl to my caps lock key, so they are more or less equivalent to me.  I chose cmd+ctrl only because it seemed like the smallest overall potential change that would solve my issue.

**Comment by melted** [comment]
I'm inclined to merge this. First I'll run it by Edwin.

**Comment by melted** [comment]
@karljs To avoid causing trouble for the book, it would be best to keep the old keys too. Can you make a patch where both key combinations are valid?

**Comment by karljs** [comment]
Sorry for the slow response.  I'll try to get that done in the next few days if possible.

**Comment by karljs** [comment]
@melted @archaeron I've finally updated this to allow both sets of keybindings on OS X.  I've only done some very cursory testing so please let me know if this isn't the right solution.

**Pull request merged**
