### PR TITLE
Copy path of executable to clipboard

### PR DESCRIPTION
**Pull request by justjoheinz**
Relates to #138.
Copy the path of `:exec expr` to the clipboard and present a atom notification.
This solution is not ideal, but I could not find a comint buffer for atom.

### CODE REVIEW

**Comment by david-christiansen** [comment]
Could something like https://atom.io/packages/script-runner be used to run the executable?

**Comment by justjoheinz** [comment]
Thank you @david-christiansen  - This looks promising, I had a look at various packages in different states of mayhem. I will see if I can get this to work.

**Comment by justjoheinz** [comment]
https://github.com/ioquatix/script-runner/issues/77
I check with the folks of script-runner whether they are willing to expose their API as a service.

**Comment by melted** [comment]
Thanks!

@justjoheinz I invited you as a member of idris-hackers so you can merge good stuff yourself

**Comment by melted** [comment]
And I really should make a release. I just have to fix the async stuff for Atom 1.19.

**Pull request merged**
