### PR TITLE
add Ipkg support

### PR DESCRIPTION
**Pull request by archaeron**
This is a work in progress for #29

### CODE REVIEW

**Comment by archaeron** [comment]
added simple ipkg highlighting
ipkg_file

**Comment by david-christiansen** [comment]
That looks pretty good! In the Emacs mode, we also have commands to call `idris --build` and such on the `.ipkg` files. This might be nice to have. Is there a way to embed a terminal in Atom?

**Comment by archaeron** [comment]
Good idea to add the commands :+1:

Do you mean something like this? https://atom.io/packages/terminal-status
There are many many packages like that one, but I haven't tried them out yet. Not sure how many of them work across more than one OS :)

**Comment by david-christiansen** [comment]
I was thinking more just something where the output of the commands could be displayed and, if you're feeling fancy, interacted with.  For example, in `idris-mode` for Emacs, it lists the file names as it checks them, and then you can click on them to jump to the file in question. Likewise for error messages that occur.

**Comment by david-christiansen** [comment]
Also, the `--testpkg` command can cause arbitrary terminal IO to occur, so for that it might be nice to have some kind of braindead terminal emulator inside of Atom to interact with the test suite, if only to see its output.

**Comment by archaeron** [comment]
I'ts not too hard to build what you describe. I don't think there is a ready made solution for this.
I like what you say about the `idris-mode` with the files being listed as they are typechecked.

Could we combine this with a REPL? maybe output it in thre REPL but with different coloring to make it clear that it is compiler output?

**Comment by david-christiansen** [comment]
In Emacs, the convention is to do it in a different pane, but it might be that intermixing it into the REPL is more in line with Atom conventions. Hard to say :)

**Comment by archaeron** [comment]
it probably isn't :D
just thinking aloud.

Do I need a real parser for the ipkg files or would a RegExp be enough?

**Comment by david-christiansen** [comment]
The Emacs mode uses regexps for the highlighting in there, plus some custom code to make module names clickable and such. I'd like to get compiler-supported `ipkg` highlighting, but I think it's a bit low priority.

**Comment by archaeron** [comment]
I meant regexps to parse the ipkg file and extract the `opts` :).

And something like
```
idris --ide-mode -ipkg highlighter.ipkg Parser.idr
```
would be cool.

**Comment by david-christiansen** [comment]
Yeah, that's how the Emacs mode grabs the opts. I agree that Idris should do that for us! It's silly to replicate code in elisp and the Atom plugin, after all.

**Comment by david-christiansen** [comment]
I think it might be better to just have a command line that pulls the options out, though, because then the  editors can check for changes in the options field more easily and restart Idris with the new options if necessary.

**Comment by archaeron** [comment]
That would be fine for me too. And it sounds a lot easier to implement on the idris side.

Just out of curiosity: why are the packages not supplied as a list?
like
```
deps =
  [
    lightyear,
    crypto
  ]
```

**Comment by david-christiansen** [comment]
Ease of implementation shouldn't stop us from doing the right thing - I just think that the right thing in this case is to have commands for extracting ipkg fields, rather than just one to run it. It's a lower-level building block, which allows for more flexibility.

The dependencies probably should be supplied as a list. The .ipkg format is basically a weekend hack by Edwin a while back. It could also use lots of other features, like dependency versions, auto-checkout of Git repos in the style of Bower and Cargo, specification of non-code resource files like images or help text, and much more. Once your sweet highlighting package is working, you could consider looking into throwing together a better package system in Idris itself as a way to make something practical and really make a difference in the language :)

**Comment by archaeron** [comment]
Sorry, I didn't mean to say we should do it because it's easy. I meant more: it's easier and it works (better) :)
Best kind of solution.

Sounds like a very goo plan to learn and do something useful! :)
I'd really like to work on the highlighting package, but all the commands of the atom package don't work yet on the project :D That's why this branch is important.

**Comment by david-christiansen** [comment]
Always nice to eat one's own dogfood!

**Comment by archaeron** [comment]
@jeremy-w thanks a lot for looking at some of the commits :)
if you have time to look at the latest ones it would be great. I think this branch is ready to merge.
If you don't have time that's okay too. Will merge probably soon if noone reports an issue.

**Pull request merged**
