### PR TITLE
Type and docs highlighting

### PR DESCRIPTION
**Pull request by archaeron**
Adds highligting to the type and documentation views

features:

- highlighting comes from the idris compiler
- easy to add to a new view
- testable

Before:
without-highlighting

After:
with-highlighting

### CODE REVIEW

**Comment by Heather** [comment]
when I open file from context menu with atom it doesn't load and first time I used to get:
```
Uncaught TypeError: Cannot read property 'stdin' of undefined
/C:/Users/Rainbow/.atom/packages/language-idris/lib/idris-model.coffee:136
```

but mostly just blank file, if I reopen editor file loads fine but if I close and reopen idris file I see blank pane, it doesn't load

**Comment by archaeron** [comment]
could it be that the idris code you where working with had errors in it? I think there is an issue when you work on invalid code. The ide-mode seems to stop. We should start a new one when this happens. I think it's unrelated to this pull request though.

**Comment by Heather** [comment]
@archaeron it's not related error but outdated .ibc but yes, that could be different issue

**Comment by archaeron** [comment]
I've created an inssue here: https://github.com/idris-hackers/atom-language-idris/issues/13

**Pull request merged**
