### PR TITLE
Proving

### PR DESCRIPTION
**Pull request by archaeron**
This is the pullrequest for #12 

I'm working through this [video](https://www.youtube.com/watch?v=0eOY1NxbZHo&list=PLiHLLF-foEexGJu1a0WH_llkQ2gOKqipg) until I can prove something.
- [x] Metavariables
- [x] Add Clause
- [x] Case Split
- [x] Proof Search

### CODE REVIEW

**Comment by archaeron** [comment]
Metavaraibles view:
metavariables

**Comment by archaeron** [comment]
@Heather what do you think? should we merge this?
all four points above work on my computer.

**Comment by Heather** [comment]
@archaeron I will try today in ~5 hours

**Comment by Heather** [comment]
tested locally, looks good to me, I can't verify `full` functionality but it works fine

**Comment by archaeron** [comment]
thanks a lot!

I will add an entry to the tutorial later.

**Pull request merged**
