### PR TITLE
Add a repl that opens in an atom tab

### PR DESCRIPTION
**Pull request by archaeron**
First look:

idris_repl_panel_2

### CODE REVIEW

**Comment by archaeron** [comment]
screen shot 2015-10-22 at 14 23 48

**Comment by Heather** [comment]
:+1:

**Comment by archaeron** [comment]
Handle errors without crashing.

idris_repl_panel_3

**Comment by archaeron** [comment]
Apropos panel with tooltip.

idris_apropos_panel_1

**Comment by david-christiansen** [comment]
Lookin' good!

**Comment by archaeron** [comment]
Thanks :)

This is now in master. I'll need to search for some testers in IRC.

**Pull request merged**
