### PR TITLE
New Shortcuts

### PR DESCRIPTION
**Pull request by archaeron**
I propose new shortcuts, so that we don't pollute the shortcut namespace.

and it's easyer to remember, because they all start with `ctrl-alt-a`.

What do you think?

### CODE REVIEW

**Comment by Heather** [comment]
Looks good for me

**Comment by david-christiansen** [comment]
Isn't it difficult to type lots of Ctrl-alt shortcuts? It might be easier to type if you also have an alias where the second letter is also with Ctrl-Alt, like Ctrl-Alt-a Ctrl-Alt-p in addition to Ctrl-Alt-a p.

**Comment by archaeron** [comment]
you are right, it is difficult.
I'll try to find some free shortcuts

`ctrl-q`, `alt-a`, `alt-c`, `alt-w`

what would be the best approach to find the second letter? how near it is to the left hand? or that it is the same as the first letter of the command?

**Comment by david-christiansen** [comment]
To be honest, I don't know enough about Atom conventions to say. What do other Atom modes do?

**Comment by Heather** [comment]
what about `ctrl-x`

As emacs user you should like it, not sure if that is available

**Comment by archaeron** [comment]
`ctrl-x` is taken on windows at least by `cut`. But that would have been a nice combination.

I've searched for some keymaps and found this one: https://github.com/OmniSharp/omnisharp-atom/blob/master/keymaps/omnisharp-atom.cson

looks pretty random to me. I think we can use whatever we want as long as it doesn't conflict with default atom keybindings. They are only active on an editor with a loaded Idris file, so we don't disturb other packages.

**Comment by archaeron** [comment]
What about `ctrl-q`? It feels comfortable to use with one hand.

- Case-splitting (`ctrl-q s`)
- Clause-adding (`ctrl-q a`)
- Proof-search (`ctrl-q p`)
- Showing the types of variables (`ctrl-q t`)
- Show the doc of a variable (`ctrl-q d`)

And we could add aliases like @david-christiansen said, like `ctrl-q ctrl-s`

**Comment by Heather** [comment]
`ctrl-q` feels dangerous for me, it closes things often...

**Comment by archaeron** [comment]
@Heather you are right. And this is harder than I thought.
Do you agree that having a single starting point for all your shortcuts is a good idea though?

**Comment by Heather** [comment]
@archaeron I don't mind, I don't use this shortcuts often anyways...

**Comment by archaeron** [comment]
ok, let's leave this open for now. Maybe someone has an idea.

thanks for the input

**Comment by archaeron** [comment]
I'm closing this until someone wants different shortcuts

**Pull request closed without merging**
