### PR TITLE
Codecompletion via autocomplete-plus

### PR DESCRIPTION
**Pull request by justjoheinz**
Please review! Do not merge, yet.
There is a problem with
```
@model.replCompletions prefix
```
in the sense that I need to type check the file once to get an instance of the model. I do not know how to get around that. Otherwise it works very nicely.

### CODE REVIEW

**Comment by archaeron** [comment]
Hello
thanks a lot for this start.
I made two changes in a branch for you to look:

First i catch all the errors to make it easier to se the function that loads an eventual ipkg file.
This is more to make the code look better in general.
https://github.com/idris-hackers/atom-language-idris/commit/72914c165e3d1f748abdfc4242bc203ca3bf97a9

And then I initialize the model before doing the replCompletion
https://github.com/idris-hackers/atom-language-idris/commit/cda2a3c4a8b740f78681ac5a974cd93075ded4f0

Does this fix your problem?

**Comment by justjoheinz** [comment]
Cool, this should be fine now. thanks for the help. I adjusted the completer a little bit that it is slightly less aggressive. It can always be triggered manually, or will trigger (depending on the autocomplete+ settings) when the length of the word being considered is > 2
AFAIK it can be merged.

**Comment by justjoheinz** [comment]
@archaeron Anything that still needs to be done? I'd like to see this get through before submitting a PR for the atom linter package.

**Comment by archaeron** [comment]
@justjoheinz hey
sorry, I'm pretty busy.

It looks good. The only small issue I have at the moment is that it marks every suggestion as `function`.
Do you want me to merge it now and we fix it later?

**Comment by justjoheinz** [comment]
I am in favor of merging, because I can get the linter changes in afterwards. Regarding the "mark everything as function" - do you happen to know how this can be avoided. AFAIK idris just returns strings, and we do not know what they are.

**Comment by archaeron** [comment]
I'll merge :+1: 

I thought I'd seen a field that tells us what Idris is returning. But I might be mistaken.
I'll have to try this evening hopefully.

**Pull request merged**
