### PR TITLE
Make make-case and make-with text insertion more robust

### PR DESCRIPTION
**Pull request by jmanuel1**
I've changed the text replacement functions to make sure they insert text at the beginning of the line and add a newline at the end. Also, I've tried to make sure that auto-indentation doesn't mess the text we insert.

### CODE REVIEW

**Comment by jmanuel1** [comment]
https://github.com/idris-hackers/atom-language-idris/assets/7255867/772ee4f3-9c1a-43bb-a0ba-495ad71c7618

**Comment by archaeron** [comment]
hi :)

thank you for this. I haven't worked on this in a while and I'm happy to merge this if it's ready, but I'm not fully sure how to relase this as I haven't dont this in a long time

**Comment by melted** [comment]
I think I can give commit rights to @jmanuel1 if wanted. I believe release is just a matter of tagging with a version.

**Comment by archaeron** [comment]
@jmanuel1 has already added some commits to the main branch so I think giving him commit rights would make sense.

And I thought I remember I had to do something with: https://github.com/atom/apm

**Comment by jmanuel1** [comment]
Given the [Atom sunset](https://github.blog/2022-06-08-sunsetting-atom/), I'm not sure publishing through apm will work. IDK if atom-community has a package registry running yet, but Pulsar (the Atom fork I'm using) does, so we could push a new version there.

**Comment by jmanuel1** [comment]
Also, the PR is ready (imo).

**Pull request merged**
