### PR TITLE
[WIP] well typed idris protocol

### PR DESCRIPTION
**Pull request by archaeron**
- replaced bennu and nu-stream with parjs, because the old libraries had no typescript support
- converted the tests to typescript

### CODE REVIEW

**Comment by meraymond2** [comment]
Hi, I finished the first release of a well-typed Idris protocol library a few weeks ago. When I started it, your similar project didn't have any recent commits. 

I did it for a new vs-code plugin, but made it as a separate library in case it could be re-used. I'd be happy to collaborate on something for both plugins, though I completely understand if you want to maintain your own. :slightly_smiling_face:  

https://github.com/meraymond2/idris-ide-client

**Comment by archaeron** [comment]
@meraymond2 no I would totally want to work together and having a single backend would be great!
Also we should probably switch to the LSP approach on Atom as well

**Comment by archaeron** [comment]
@meraymond2 you can easily install idris2 via nix (at least version 0.2.0)

```
nix-shell -p idris2
[nix-shell:~/]$ idris2 --version
Idris 2, version 0.2.0
```

**Comment by archaeron** [comment]
I would prefer this approach:

https://github.com/idris-hackers/atom-language-idris/pull/251

**Comment by meraymond2** [comment]
> @meraymond2 you can easily install idris2 via nix (at least version 0.2.0)
> 
> ```
> nix-shell -p idris2
> [nix-shell:~/]$ idris2 --version
> Idris 2, version 0.2.0
> ```

That is a very good point, I completely forgot to check unstable.

**Pull request closed without merging**
