### PR TITLE
Updated deprecations

### PR DESCRIPTION
**Pull request by archaeron**
- most of the deprecations should be gone
- there is a new parser and a new serializer for the ide-mode commands that should work more reliably

### CODE REVIEW

**Comment by archaeron** [comment]
@Heather could you test this on your machine?

**Comment by Heather** [comment]
@archaeron sure, I will try it tomorrow

**Comment by Heather** [comment]
@archaeron strange but it can't find idris in my path

**Comment by archaeron** [comment]
@Heather could you elaborate this further? Do you mean you cloned it into the package directory with another name than atom-language-idris?

**Comment by Heather** [comment]
@archaeron here: https://github.com/idris-hackers/atom-language-idris/blob/master/lib/language-idris.coffee#L17

**Comment by archaeron** [comment]
but what triggered the error? is it working now?

**Comment by Heather** [comment]
@archaeron if directory name is not `atom-language-idris` then it will not find config file

**Comment by archaeron** [comment]
Do you think this will be a problem if someone installs the package from atom whan we publish it?
To be honest I'm not entirely sure what string the config wants.
https://atom.io/docs/api/v0.201.0/Config <- here it doesn't tell if it's the name of the folder or if it's the name of the package.
Problably the name of the folder judging from your problem. And this is strange.

**Comment by Heather** [comment]
@archaeron from my experience it's the name of folder and it's not big problem if folder is named same way. But maybe it will be good idea to name package `language-idris` because all other packages follow that naming rule and then it possibly will be a problem.

**Comment by archaeron** [comment]
the package is already called language-idris: https://atom.io/packages/language-idris

But if we're allowed to rename the repository to language-dris too that would be great :)
could you ask someone from idris-hackers? :)

**Comment by Heather** [comment]
@archaeron you can clone it to `language-idris` and if it's using as `language-idris` in package then we can just change this line: https://github.com/idris-hackers/atom-language-idris/blob/master/lib/language-idris.coffee#L17

**Comment by archaeron** [comment]
@Heather you are right. but it would be cool to rename the repository too. so that we can clone without changing the name

**Comment by Heather** [comment]
@archaeron yes but `language-idris` could be confusing name, we should ask on irc

**Comment by archaeron** [comment]
we should :) I changed the config btw.
https://github.com/idris-hackers/atom-language-idris/commit/5eea2b297e30603dfc04e5f0c4ae9c702fd4b9e1

**Comment by david-christiansen** [comment]
I think calling the Github repo "language-idris" will confuse people looking at the repository list. They might think that it actually contains the Idris language, or that it's something more general.

**Comment by archaeron** [comment]
@david-christiansen you're right. I'll write something into the readme that one has to clone it into language-idris for development. thank you

**Comment by fangel** [comment]
This is mostly based off of a hunch, but if you install the plugin through APM, doesn't the checkout get the right name (language-idris). So isn't this only a problem for development?

**Comment by Heather** [comment]
yes, readme note will be enough

**Comment by archaeron** [comment]
@fangel yes, it's just an inconvenience fir development. Not a problem though.
I've updated the readme: https://github.com/idris-hackers/atom-language-idris/commit/888d1d618e829707d5a0dd38e3d5266b6c14ae3d

**Pull request merged**
